wandb_version: 1

T:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1661376037.002783
    t:
      1:
      - 1
      - 53
      - 55
      2:
      - 1
      - 53
      - 55
      3:
      - 16
      - 17
      - 23
      - 37
      4: 3.8.13
      5: 0.13.2
      8:
      - 4
      - 5
batch_size:
  desc: null
  value: 32
burn_in:
  desc: null
  value: null
checkpoint_freq:
  desc: null
  value: 100
dataset:
  desc: null
  value: data/12173/12173.e.cleaned
decay_length:
  desc: null
  value: null
decay_step:
  desc: null
  value: null
dim:
  desc: null
  value: 33
distloss:
  desc: null
  value: false
edim:
  desc: null
  value: 33
epochs:
  desc: null
  value: 1000
euc:
  desc: null
  value: 3
exponential_rescale:
  desc: null
  value: null
extra_steps:
  desc: null
  value: null
hyp:
  desc: null
  value: 3
lazy_generation:
  desc: null
  value: false
learn_scale:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.001
log:
  desc: null
  value: false
log_name:
  desc: null
  value: null
logloss:
  desc: null
  value: false
model_load_file:
  desc: null
  value: null
model_save_file:
  desc: null
  value: null
momentum:
  desc: null
  value: null
num_workers:
  desc: null
  value: null
print_freq:
  desc: null
  value: null
resample_freq:
  desc: null
  value: null
riemann:
  desc: null
  value: false
sample:
  desc: null
  value: false
scale:
  desc: null
  value: null
sdim:
  desc: null
  value: 33
sph:
  desc: null
  value: 3
squareloss:
  desc: null
  value: false
subsample:
  desc: null
  value: 16
symloss:
  desc: null
  value: false
tol:
  desc: null
  value: null
use_adagrad:
  desc: null
  value: false
use_hmds:
  desc: null
  value: false
use_svrg:
  desc: null
  value: false
use_yellowfin:
  desc: null
  value: false
visualize:
  desc: null
  value: false
warm_start:
  desc: null
  value: false
